version: '3'
services:
    web:
        build: ./zoo-flask-app
        expose:
            - 5000
        volumes:
            - .:/code
        depends_on:
            - db
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_USER: 'dtpoc'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'Zoo-Flask-App'
      ports:
        - "32000:3306"
      volumes:
        - my-db:/var/lib/mysql
    nginx:
      build: ./nginx
      ports:
      - 1337:80
      depends_on:
      - web
volumes:
  my-db: