"""empty message

Revision ID: 101415963bde
Revises: 
Create Date: 2020-01-29 12:27:02.164294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101415963bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Animal')
    # ### end Alembic commands ###
